import { Palette } from "../palette.slint";

export component BorderVertical inherits Rectangle {
    in-out property <length> size: 1px;
    
    y: 0;
    width <=> size;
    background: Palette.borders;
}

export component BorderVerticalResize inherits Rectangle {
    in-out property <length> size: 1px;
    in property <color> border-left-color;
    in property <color> border-right-color;

    callback resize(length);
    
    y: 0;
    width: 4px + size;

    touch := TouchArea {
        mouse-cursor: ew-resize;
        moved => {
            root.resize(self.mouse-x - self.pressed-x)
        }
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                left.background = Palette.primary;
                border.background = Palette.primary;
                right.background = Palette.primary;
            } else if (event.kind == PointerEventKind.up) {
                left.background = border-left-color;
                border.background = Palette.borders;
                right.background = border-right-color;
            }
        }
    }

    left := Rectangle {
        x: 0;
        width: 2px;
        background: border-left-color;
    }

    border := Rectangle {
        x: 1px;
        width <=> size;
        background: Palette.borders;
    }

    right := Rectangle {
        x: 1px + size;
        width: 2px;
        background: border-right-color;
    }
}

export component BorderHorizontal inherits Rectangle {
    y: 0;
    height: 1px;
    background: Palette.borders;
}