import { Palette } from "../palette.slint";
export struct HierarchyEntry {
    id: string,
    title: string,
    folded: bool,
    identation: int,
    is_folder: bool,
}

component HierarchyElement inherits Rectangle {
    in-out property <HierarchyEntry> entry;

    callback clicked(string, bool);

    height: 25px;

    ta := TouchArea {
        clicked => {
            root.clicked(entry.id, entry.is-folder);
        }
    }
    
    Text {
        x: 15px + (10px * entry.identation);
        text: (entry.is_folder ? entry.folded ? " " : " " : " ") + entry.title;
    }

    states [
        hovered when ta.has-hover: {
            background: Palette.background-main-hover;
        }
        not-hovered when !ta.has-hover: {
            background: Palette.background-main;
        }
    ]
}

export component Hierarchy inherits Rectangle {
    in-out property <[HierarchyEntry]> entries;

    callback clicked_entry(string, bool);

    VerticalLayout {
        for entry in entries: HierarchyElement {
            width: parent.width;
            entry: entry;
            clicked(id, is-folder) => {
                root.clicked_entry(id, is-folder)
            }
        }
    }
}