import { Palette } from "../palette.slint";
import "../../resources/fonts/lineicons.ttf";

export component SidebarButton inherits Rectangle {
    in-out property <string> icon <=> icon.text;
    in-out property <bool> active: false;

    height: 47px;
    width: 47px;

    ta := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            active = !active
        }
    }

    active-indicator := Rectangle {
        x: 0;
        y: 0;
        
        background: Palette.primary;

        states [
            active when active : {
                width: 3px;
            }
            inactive when !active : {
                width: 0px;
            }
        ]
    }

    icon := Text {
        font-family: "lineicons";
        font-size: 28px;

        states [
            active when active: {
                color: Palette.sidebar-text-active;
            }
            hovered when ta.has-hover: {
                color: Palette.sidebar-text-hover;
            }
            neutral when !active && !ta.has-hover: {
                color: Palette.sidebar-text;
            }
        ]
        
    }
}