import { SidebarMenu } from "sidebar-menu.slint";
import { BorderVertical, BorderVerticalResize } from "borders.slint";
import { SidebarSubMenu } from "sidebar-submenu.slint";
import { Palette } from "../palette.slint";
export component Sidebar inherits Rectangle {
    HorizontalLayout {
        property <length> submenu-size: 500px;

        SidebarMenu {}

        BorderVertical {}

        SidebarSubMenu {
            size <=> submenu-size;
        }

        BorderVerticalResize {
            border-left-color: Palette.background-main;
            border-right-color: Palette.background-secondary;
        }
    }
}