import { Palette } from "../palette.slint";
import "../../resources/fonts/lineicons.ttf";

export component SidebarButton inherits Rectangle {
    in-out property <string> icon <=> icon.text;
    in-out property <bool> active: false;

    height: 47px;
    width: 47px;

    ta := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            active = !active
        }
    }

    icon := Text {
        font-family: "lineicons";
        font-size: 28px;

        states [
            active when ta.has-hover: {
                color: Palette.sidebar-text-hover;
            }
            inactive when !ta.has-hover: {
                color: Palette.sidebar-text;
            }
        ]
        
    }
}