import { SidebarMenu } from "sidebar-menu.slint";
import { BorderVertical, BorderVerticalResize } from "borders.slint";
import { SidebarSubMenu } from "sidebar-submenu.slint";
import { Palette } from "../palette.slint";
export component Sidebar inherits Rectangle {
    property <length> submenu-size: 500px;
    
    HorizontalLayout {
        SidebarMenu {}

        BorderVertical {}

        SidebarSubMenu {
            size <=> submenu-size;
        }

        BorderVerticalResize {
            border-left-color: Palette.background-main;
            border-right-color: Palette.background-secondary;
            resize(movement) => {
                if (root.submenu-size + movement < 169px) {
                    root.submenu-size = 169px;
                } else {
                    root.submenu-size += movement
                }
            }
        }
    }
}