import { BorderHorizontal, BorderVertical } from "borders.slint";
import { Palette } from "../palette.slint";
component TabButton inherits Rectangle {
    in-out property <string> title;
    in-out property <bool> active;

    callback clicked();

    width: 100px;

    ta := TouchArea {
        clicked => {
            root.clicked();
        }
    }

    if root.active: BorderHorizontal {
        background: Palette.primary;
    }

    HorizontalLayout {
        padding-left: 15px;
        
        Text {
            y: 11px;
            text <=> root.title;
            font-size: 14px;
            font-family: "Lora";
            states [
                active when root.active: {
                    color: Palette.text;
                }
                inactive when !root.active: {
                    color: Palette.text-inactive;
                }
            ]
        }

        BorderVertical {}
    }

    if !active: BorderHorizontal {
        y: parent.height - 1px;
    }

    states [
        active when self.active: {
            background: Palette.background-secondary;
        }
        hovered when ta.has-hover: {
            background: Palette.background-secondary;
        }
        not-hovered when !ta.has-hover: {
            background: Palette.background-main;
        }
    ]
}

export component Tabs inherits VerticalLayout {
    in-out property <int> active_tab;

    HorizontalLayout {
        height: 40px;

        TabButton {
            title: "Tab 1";
            height: parent.height;
            active: 0 == active_tab;
            clicked => {
                active_tab = 0;
            }
        }

        TabButton {
            title: "Tab 2";
            height: parent.height;
            active: 1 == active_tab;
            clicked => {
                active_tab = 1;
            }
        }

        Rectangle {
            background: Palette.background-main;
            BorderHorizontal {
                y: parent.height - 1px;
            }
        }
    }

    Rectangle {
        background: Palette.background-secondary;
    }
}