import { SidebarMenu, Menu } from "sidebar-menu.slint";
import { BorderVertical, BorderVerticalResize } from "../../components/borders.slint";
import { SidebarSubMenu } from "sidebar-submenu.slint";
import { Palette } from "../../palette.slint";
import { SubMenu } from "submenus/submenu.slint";
import { GeneratorsSubMenu } from "submenus/generators.slint";
import { FiltersSubMenu, FilterEntry } from "submenus/filters.slint";
import { SettingsSubMenu } from "submenus/settings.slint";
import { HierarchyEntry } from "./submenus/hierarchy.slint";
export component Sidebar inherits Rectangle {
    property <length> submenu-size: 350px;
    property <bool> resizable-border-displayed: true;
    property <Menu> current-menu : Menu.Generators;

    in-out property <string> current_workspace;
    in-out property <[string]> workspaces;
    in-out property <[HierarchyEntry]> generation_entries;
    in-out property <[FilterEntry]> filters;
    
    callback workspace_changed <=> generators-menu.workspace_changed;
    callback generators_entry_selected(string, string, bool);
    callback filter_searched_tags(string);
    callback reverse_filter_activation(string);
    callback reset_filters(string);

    HorizontalLayout {
        SidebarMenu {
            menu_change(menu) => {
                if (menu == Menu.Closed) {
                    submenu-size = 0px;
                    resizable-border-displayed = false;
                } else if submenu-size == 0px {
                    submenu-size = 350px;
                    resizable-border-displayed = true;
                }
                current-menu = menu;
            }
        }

        BorderVertical {}

        SidebarSubMenu {
            size <=> submenu-size;

            generators-menu := GeneratorsSubMenu {
                visible: current-menu == Menu.Generators;
                current_workspace <=> current_workspace;
                workspaces <=> workspaces;
                entries <=> generation_entries;
                entry_selected(id, is-folder) => {
                    root.generators_entry_selected(current_workspace, id, is-folder)
                }
            }

            filters-menu := FiltersSubMenu {
                filters <=> filters;
                visible: current-menu == Menu.Filters;
                filter_searched_tags(searched) => {
                    root.filter_searched_tags(searched);
                }
                reverse_filter_activation(filter_name) => {
                    root.reverse_filter_activation(filter_name);
                }
                reset_filters(current_searched) => {
                    root.reset_filters(current_searched);
                }
            }

            settings-menu := SettingsSubMenu {
                visible: current-menu == Menu.Settings;
            }
        }

        BorderVerticalResize {
            border-left-color: Palette.background-main;
            size: resizable-border-displayed ? 1px : 0px;
            resize(movement) => {
                if (root.submenu-size + movement < 169px) {
                    root.submenu-size = 169px;
                } else {
                    root.submenu-size += movement
                }
            }
        }
    }
}