import { SubMenu } from "./submenu.slint";
import { Textbox } from "../../../components/textbox.slint";
import { LineEdit, ScrollView, Switch } from "std-widgets.slint";
import { Button } from "../../../components/button.slint";

export struct FilterEntry {
    name: string,
    enable: bool,
}

component FilterDisplay inherits Rectangle {
    in-out property <FilterEntry> filter;

    callback reverse_filter_activation(string);

    height: 25px;

    HorizontalLayout {
        padding-left: 15px;
        padding-right: self.padding-left;

        Text {
            font-size: 14px;
            font-family: "Lora";
            text: filter.name;
        }
        
        Switch {
            text: "";
            checked: filter.enable;
            toggled => {
                filter.enable = !filter.enable;
                root.reverse_filter_activation(filter.name);
            }
        }
    }
}

export component FiltersSubMenu inherits SubMenu {
    title: "FILTERS";

    in-out property <[FilterEntry]> filters;
    property <string> searched;

    callback filter_searched_tags(string);
    callback reverse_filter_activation(string);
    callback reset_filters(string);

    Rectangle {
        height: 26px;

        Textbox {
            icon: "";
            width: parent.width - 20px;
            text <=> searched;
            edited(searched) => {
                root.filter_searched_tags(searched);
            }
        }
    }

    Rectangle {
        height: 10px;
    }

    Button {
        x: 10px;
        width: parent.width - 20px;
        text: "Reset all filters";
        clicked => {
            root.reset_filters(root.searched);
        }
    }

    Rectangle {
        height: 10px;
    }

    ScrollView {
        VerticalLayout {
            for filter in filters: FilterDisplay {
                filter: filter;
                reverse_filter_activation(filter_name) => {
                    root.reverse_filter_activation(filter_name);
                }
            }
        }
    }
}