import { SubMenu } from "./submenu.slint";
import { ScrollView, ComboBox } from "std-widgets.slint";
import { Palette } from "../../../palette.slint";
import { CustomComboBox } from "../../../components/combobox.slint";
import { Hierarchy, HierarchyEntry } from "./hierarchy.slint";

export component GeneratorsSubMenu inherits SubMenu {
    in-out property <string> current_workspace;
    in-out property <[string]> workspaces;
    in-out property <[HierarchyEntry]> entries;

    callback workspace_changed <=> workspace-selector.selected;
    callback entry_selected <=> hierarchy.entry_selected;

    title: "GENERATORS";

    Rectangle {
        height: 26px;

        workspace-selector := CustomComboBox {
            width: parent.width - 20px;
            model <=> workspaces;
            active_option <=> current_workspace;
        }
    }

    Rectangle {
        height: 10px;
    }

    ScrollView {
         hierarchy := Hierarchy {
            entries <=> entries;
         }
    }
}