import { Palette } from "../../../palette.slint";
export component SubMenu inherits VerticalLayout {
    in property <string> title;

    VerticalLayout {
        Rectangle {
            
            height: 36px;

            Text {
                x: 20px;
                y: 10px;

                font-size: 14px;
                font-family: "Lora";
                text: title;
                color: Palette.text;
            }
        }

        @children
    }
}