import { SubMenu } from "../submenu.slint";
import { ScrollView, ComboBox } from "std-widgets.slint";
import { Palette } from "../../../palette.slint";
import { CustomComboBox } from "../../combobox.slint";
import { Hierarchy, HierarchyEntry } from "../../hierarchy.slint";

export component GeneratorsSubMenu inherits SubMenu {
    in-out property <string> current_workspace;
    in-out property <[string]> workspaces;
    in-out property <[HierarchyEntry]> entries;

    title: "GENERATORS";

    Rectangle {
        height: 20px;

        CustomComboBox {
            width: parent.width - 20px;
            model <=> workspaces;
            active_option <=> current_workspace;
        }
    }

    Rectangle {
        height: 10px;
    }

    ScrollView {
         Hierarchy {
            entries <=> entries;
         }
    }
}