import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Palette } from "palette.slint";
import { BorderVertical, BorderHorizontal } from "./components/borders.slint";
import "../resources/fonts/lineicons.ttf";
import { Sidebar } from "components/sidebar/sidebar.slint";
import { MainMenu } from "components/main-menu.slint";
import { HierarchyEntry } from "components/hierarchy.slint";

enum SidebarButtonPosition {
    Top,
    Bottom
}

struct SidebarButtonData {
    icon: string,
    position: SidebarButtonPosition,
    active: bool,
}

export component AppWindow inherits Window {
    preferred-width: 1024px;
    preferred-height: 768px;

    in-out property <string> current_workspace;
    in-out property <[string]> workspaces;
    in-out property <[HierarchyEntry]> generation_entries;

    callback generator_entry_clicked(string);

    VerticalLayout {
        MainMenu {}

        BorderHorizontal {}

        Rectangle {
            x: 0;
            
            HorizontalLayout {
                Sidebar {
                    current_workspace <=> current_workspace;
                    workspaces <=> workspaces;
                    generation_entries <=> generation_entries;
                    generator_entry_clicked(id) => {
                        root.generator_entry_clicked(id);
                    }
                }

                content := Rectangle {
                    y: 0;
                    
                    background: Palette.background-secondary;
                }
            }
        }
    }
}
