export global Palette {
    
    // ----------------- BACKGROUNDS ------------------------
    out property<color> background-main: #f8f8f8;
    out property<color> background-secondary: #ffffff;

    // ----------------- ACCENT COLORS ----------------------
    out property<color> primary: #06D6A0;

    // ----------------- TEXT -------------------------------
    out property<color> sidebar-text: #808080;
    out property<color> sidebar-text-hover: #1e1e1e;
    out property<color> sidebar-text-active: sidebar-text-hover;

    // ----------------- OTHERS -----------------------------
    out property<color> borders: #e5e5e5;
}