export global Palette {
    
    // ----------------- BACKGROUNDS ------------------------
    out property<color> background-main: #f8f8f8;
    out property<color> background-secondary: #ffffff;

    // ----------------- ACCENT COLORS ----------------------
    out property<color> primary: #06D6A0;

    // ----------------- OTHERS -----------------------------
    out property<color> borders: #e5e5e5;
}